name: env
channels:
 - defaults
dependencies:
 - pip=19.3.1=py37_0
 - protobuf=3.9.2=py37he6710b0_0
 - python=3.7.0=h6e4f718_3
 - setuptools=41.6.0=py37_0
 - sqlite=3.30.1=h7b6447c_0
 - tensorboard=2.0.0
 - tensorflow=2.0.0
 - tensorflow-base=2.0.0
 - tensorflow-estimator=2.0.0
 - pip:
   - torch==1.3.1
   - numpy==1.18.0
   - pandas==0.25.3
   - scikit-learn==0.21.3
   - scipy==1.2.0
prefix: /opt/conda/envs/env